# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.page_session_event import PageSessionEvent
from ..types.page_session_summary import PageSessionSummary
from ..types.quota_status import QuotaStatus
from ..types.session import Session
from ..types.session_changes import SessionChanges
from ..types.session_request_agent import SessionRequestAgent
from ..types.session_request_messages import SessionRequestMessages
from ..types.session_status import SessionStatus
from ..types.share_link import ShareLink
from ..types.trajectory_status import TrajectoryStatus
from .raw_client import AsyncRawSessionsClient, RawSessionsClient
from .types.list_session_events_request_sort_item import ListSessionEventsRequestSortItem
from .types.list_sessions_request_owner import ListSessionsRequestOwner
from .types.list_sessions_request_sort_item import ListSessionsRequestSortItem
from .types.send_session_messages_request_body import SendSessionMessagesRequestBody
from .types.send_session_tool_results_request_body import SendSessionToolResultsRequestBody

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SessionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSessionsClient
        """
        return self._raw_client

    def list_sessions(
        self,
        *,
        owner: typing.Optional[ListSessionsRequestOwner] = None,
        status: typing.Optional[typing.Sequence[TrajectoryStatus]] = None,
        agent: typing.Optional[typing.Sequence[str]] = None,
        group_id: typing.Optional[str] = None,
        parent_session_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        created_before: typing.Optional[dt.datetime] = None,
        created_after: typing.Optional[dt.datetime] = None,
        finished_before: typing.Optional[dt.datetime] = None,
        finished_after: typing.Optional[dt.datetime] = None,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        sort: typing.Optional[typing.Sequence[ListSessionsRequestSortItem]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PageSessionSummary:
        """
        List sessions visible to ``user``.

        Parameters
        ----------
        owner : typing.Optional[ListSessionsRequestOwner]

        status : typing.Optional[typing.Sequence[TrajectoryStatus]]

        agent : typing.Optional[typing.Sequence[str]]

        group_id : typing.Optional[str]

        parent_session_id : typing.Optional[str]

        search : typing.Optional[str]
            Case-insensitive match on the session's first message or answer.

        created_before : typing.Optional[dt.datetime]

        created_after : typing.Optional[dt.datetime]

        finished_before : typing.Optional[dt.datetime]

        finished_after : typing.Optional[dt.datetime]

        page : typing.Optional[int]
            Page number (1-based)

        size : typing.Optional[int]
            Number of items per page

        sort : typing.Optional[typing.Sequence[ListSessionsRequestSortItem]]
            Sort by field

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageSessionSummary
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.list_sessions()
        """
        _response = self._raw_client.list_sessions(
            owner=owner,
            status=status,
            agent=agent,
            group_id=group_id,
            parent_session_id=parent_session_id,
            search=search,
            created_before=created_before,
            created_after=created_after,
            finished_before=finished_before,
            finished_after=finished_after,
            page=page,
            size=size,
            sort=sort,
            request_options=request_options,
        )
        return _response.data

    def create_session(
        self,
        *,
        agent: SessionRequestAgent,
        idempotency_key: typing.Optional[str] = None,
        messages: typing.Optional[SessionRequestMessages] = OMIT,
        max_steps: typing.Optional[int] = OMIT,
        max_time_s: typing.Optional[float] = OMIT,
        idle_timeout_s: typing.Optional[int] = OMIT,
        queue: typing.Optional[bool] = OMIT,
        group_id: typing.Optional[str] = OMIT,
        parent_session_id: typing.Optional[str] = OMIT,
        overrides: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Session:
        """
        Create an agentic session.

        Parameters
        ----------
        agent : SessionRequestAgent
            Agent to run: a registered agent's name, or an inline Agent definition.

        idempotency_key : typing.Optional[str]

        messages : typing.Optional[SessionRequestMessages]
            Initial task for the agent. A plain string, a single message, or a list of messages.

        max_steps : typing.Optional[int]
            Maximum reasoning steps the agent may take. Unbounded if null.

        max_time_s : typing.Optional[float]
            Maximum wall-clock seconds the agent may run. Unbounded if null.

        idle_timeout_s : typing.Optional[int]
            Seconds to keep the session open for follow-up messages after each answer. Null ends the session as soon as the agent answers.

        queue : typing.Optional[bool]
            When the organization is at its concurrent-session limit, accept this session into a queue (status 'queued') instead of rejecting it with 429. Queued sessions start automatically, oldest first, as running sessions finish. Set to false to get an immediate 429 when no slot is available.

        group_id : typing.Optional[str]
            Optional id to group and list related sessions together.

        parent_session_id : typing.Optional[str]
            Id of the parent session, when this is a child run.

        overrides : typing.Optional[typing.Dict[str, typing.Any]]
            Per-run overrides applied to the resolved request, keyed by a dotted path. List members are selected with an explicit [field=value] clause, e.g. {"agent.environments[kind=web].start_url": "https://bing.com"}. Each value must match the type of the field its path targets.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Session
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.create_session(
            agent="agent",
        )
        """
        _response = self._raw_client.create_session(
            agent=agent,
            idempotency_key=idempotency_key,
            messages=messages,
            max_steps=max_steps,
            max_time_s=max_time_s,
            idle_timeout_s=idle_timeout_s,
            queue=queue,
            group_id=group_id,
            parent_session_id=parent_session_id,
            overrides=overrides,
            request_options=request_options,
        )
        return _response.data

    def get_session_quota(self, *, request_options: typing.Optional[RequestOptions] = None) -> QuotaStatus:
        """
        Concurrent-session quota for the authenticated user.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QuotaStatus
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.get_session_quota()
        """
        _response = self._raw_client.get_session_quota(request_options=request_options)
        return _response.data

    def get_session(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Session:
        """
        Get a session.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Session
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.get_session(
            id="id",
        )
        """
        _response = self._raw_client.get_session(id, request_options=request_options)
        return _response.data

    def cancel_session(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Cancel the session.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.cancel_session(
            id="id",
        )
        """
        _response = self._raw_client.cancel_session(id, request_options=request_options)
        return _response.data

    def get_session_status(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> SessionStatus:
        """
        Get a session's live status.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SessionStatus
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.get_session_status(
            id="id",
        )
        """
        _response = self._raw_client.get_session_status(id, request_options=request_options)
        return _response.data

    def send_session_messages(
        self,
        id: str,
        *,
        request: SendSessionMessagesRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Send a user message (single or batch).

        Parameters
        ----------
        id : str

        request : SendSessionMessagesRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from hai_agents import Client
        from hai_agents.sessions import SendSessionMessagesRequestBody_UserMessage

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.send_session_messages(
            id="id",
            request=SendSessionMessagesRequestBody_UserMessage(
                message="message",
                type="user_message",
            ),
        )
        """
        _response = self._raw_client.send_session_messages(id, request=request, request_options=request_options)
        return _response.data

    def send_session_tool_results(
        self,
        id: str,
        *,
        request: SendSessionToolResultsRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Send results for custom tool calls (single or batch).

        Parameters
        ----------
        id : str

        request : SendSessionToolResultsRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from hai_agents import Client, ToolRequest, ToolResultEvent

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.send_session_tool_results(
            id="id",
            request=ToolResultEvent(
                tool_req=ToolRequest(
                    tool_name="tool_name",
                ),
            ),
        )
        """
        _response = self._raw_client.send_session_tool_results(id, request=request, request_options=request_options)
        return _response.data

    def pause_session(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Pause the session.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.pause_session(
            id="id",
        )
        """
        _response = self._raw_client.pause_session(id, request_options=request_options)
        return _response.data

    def resume_session(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Resume the session.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.resume_session(
            id="id",
        )
        """
        _response = self._raw_client.resume_session(id, request_options=request_options)
        return _response.data

    def force_session_answer(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Ask the agent to emit a final answer on its next step.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.force_session_answer(
            id="id",
        )
        """
        _response = self._raw_client.force_session_answer(id, request_options=request_options)
        return _response.data

    def get_session_changes(
        self,
        id: str,
        *,
        from_index: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        include_events: typing.Optional[bool] = None,
        wait_for_seconds: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[SessionChanges]:
        """
        Long-poll for new events since ``from_index``; 204 if none arrive within ``wait_for_seconds``.

        Parameters
        ----------
        id : str

        from_index : typing.Optional[int]

        limit : typing.Optional[int]

        include_events : typing.Optional[bool]

        wait_for_seconds : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[SessionChanges]
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.get_session_changes(
            id="id",
        )
        """
        _response = self._raw_client.get_session_changes(
            id,
            from_index=from_index,
            limit=limit,
            include_events=include_events,
            wait_for_seconds=wait_for_seconds,
            request_options=request_options,
        )
        return _response.data

    def list_session_events(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        sort: typing.Optional[typing.Sequence[ListSessionEventsRequestSortItem]] = None,
        type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PageSessionEvent:
        """
        Paginated event history. Use ``/changes`` for live tailing.

        Parameters
        ----------
        id : str

        page : typing.Optional[int]

        size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[ListSessionEventsRequestSortItem]]

        type : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageSessionEvent
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.list_session_events(
            id="id",
        )
        """
        _response = self._raw_client.list_session_events(
            id, page=page, size=size, sort=sort, type=type, request_options=request_options
        )
        return _response.data

    def submit_session_feedback(
        self,
        id: str,
        *,
        success: bool,
        message: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Record semantic-success feedback on the whole session.

        Parameters
        ----------
        id : str

        success : bool

        message : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.submit_session_feedback(
            id="id",
            success=True,
        )
        """
        _response = self._raw_client.submit_session_feedback(
            id, success=success, message=message, request_options=request_options
        )
        return _response.data

    def submit_event_feedback(
        self,
        id: str,
        event_index: int,
        *,
        success: bool,
        message: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Record feedback on a single event in the session's history.

        Parameters
        ----------
        id : str

        event_index : int

        success : bool

        message : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.submit_event_feedback(
            id="id",
            event_index=1,
            success=True,
        )
        """
        _response = self._raw_client.submit_event_feedback(
            id, event_index, success=success, message=message, request_options=request_options
        )
        return _response.data

    def share_session(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ShareLink:
        """
        Make the session publicly readable; returns the share URL path.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ShareLink
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.share_session(
            id="id",
        )
        """
        _response = self._raw_client.share_session(id, request_options=request_options)
        return _response.data

    def unshare_session(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Revoke public access to the session.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.sessions.unshare_session(
            id="id",
        )
        """
        _response = self._raw_client.unshare_session(id, request_options=request_options)
        return _response.data

    def get_session_resource(
        self, id: str, bucket: str, key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Redirect to a presigned S3 URL for a session-owned resource.

        Parameters
        ----------
        id : str

        bucket : str

        key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            Resource bytes. The API redirects to a presigned S3 URL; SDK clients follow the redirect and receive the raw object (e.g. screenshot image bytes).

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        for _chunk in client.sessions.get_session_resource(
            id="id",
            bucket="bucket",
            key="key",
        ):
            pass
        """
        with self._raw_client.get_session_resource(id, bucket, key, request_options=request_options) as r:
            yield from r.data


class AsyncSessionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSessionsClient
        """
        return self._raw_client

    async def list_sessions(
        self,
        *,
        owner: typing.Optional[ListSessionsRequestOwner] = None,
        status: typing.Optional[typing.Sequence[TrajectoryStatus]] = None,
        agent: typing.Optional[typing.Sequence[str]] = None,
        group_id: typing.Optional[str] = None,
        parent_session_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        created_before: typing.Optional[dt.datetime] = None,
        created_after: typing.Optional[dt.datetime] = None,
        finished_before: typing.Optional[dt.datetime] = None,
        finished_after: typing.Optional[dt.datetime] = None,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        sort: typing.Optional[typing.Sequence[ListSessionsRequestSortItem]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PageSessionSummary:
        """
        List sessions visible to ``user``.

        Parameters
        ----------
        owner : typing.Optional[ListSessionsRequestOwner]

        status : typing.Optional[typing.Sequence[TrajectoryStatus]]

        agent : typing.Optional[typing.Sequence[str]]

        group_id : typing.Optional[str]

        parent_session_id : typing.Optional[str]

        search : typing.Optional[str]
            Case-insensitive match on the session's first message or answer.

        created_before : typing.Optional[dt.datetime]

        created_after : typing.Optional[dt.datetime]

        finished_before : typing.Optional[dt.datetime]

        finished_after : typing.Optional[dt.datetime]

        page : typing.Optional[int]
            Page number (1-based)

        size : typing.Optional[int]
            Number of items per page

        sort : typing.Optional[typing.Sequence[ListSessionsRequestSortItem]]
            Sort by field

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageSessionSummary
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.list_sessions()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_sessions(
            owner=owner,
            status=status,
            agent=agent,
            group_id=group_id,
            parent_session_id=parent_session_id,
            search=search,
            created_before=created_before,
            created_after=created_after,
            finished_before=finished_before,
            finished_after=finished_after,
            page=page,
            size=size,
            sort=sort,
            request_options=request_options,
        )
        return _response.data

    async def create_session(
        self,
        *,
        agent: SessionRequestAgent,
        idempotency_key: typing.Optional[str] = None,
        messages: typing.Optional[SessionRequestMessages] = OMIT,
        max_steps: typing.Optional[int] = OMIT,
        max_time_s: typing.Optional[float] = OMIT,
        idle_timeout_s: typing.Optional[int] = OMIT,
        queue: typing.Optional[bool] = OMIT,
        group_id: typing.Optional[str] = OMIT,
        parent_session_id: typing.Optional[str] = OMIT,
        overrides: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Session:
        """
        Create an agentic session.

        Parameters
        ----------
        agent : SessionRequestAgent
            Agent to run: a registered agent's name, or an inline Agent definition.

        idempotency_key : typing.Optional[str]

        messages : typing.Optional[SessionRequestMessages]
            Initial task for the agent. A plain string, a single message, or a list of messages.

        max_steps : typing.Optional[int]
            Maximum reasoning steps the agent may take. Unbounded if null.

        max_time_s : typing.Optional[float]
            Maximum wall-clock seconds the agent may run. Unbounded if null.

        idle_timeout_s : typing.Optional[int]
            Seconds to keep the session open for follow-up messages after each answer. Null ends the session as soon as the agent answers.

        queue : typing.Optional[bool]
            When the organization is at its concurrent-session limit, accept this session into a queue (status 'queued') instead of rejecting it with 429. Queued sessions start automatically, oldest first, as running sessions finish. Set to false to get an immediate 429 when no slot is available.

        group_id : typing.Optional[str]
            Optional id to group and list related sessions together.

        parent_session_id : typing.Optional[str]
            Id of the parent session, when this is a child run.

        overrides : typing.Optional[typing.Dict[str, typing.Any]]
            Per-run overrides applied to the resolved request, keyed by a dotted path. List members are selected with an explicit [field=value] clause, e.g. {"agent.environments[kind=web].start_url": "https://bing.com"}. Each value must match the type of the field its path targets.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Session
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.create_session(
                agent="agent",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_session(
            agent=agent,
            idempotency_key=idempotency_key,
            messages=messages,
            max_steps=max_steps,
            max_time_s=max_time_s,
            idle_timeout_s=idle_timeout_s,
            queue=queue,
            group_id=group_id,
            parent_session_id=parent_session_id,
            overrides=overrides,
            request_options=request_options,
        )
        return _response.data

    async def get_session_quota(self, *, request_options: typing.Optional[RequestOptions] = None) -> QuotaStatus:
        """
        Concurrent-session quota for the authenticated user.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QuotaStatus
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.get_session_quota()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_session_quota(request_options=request_options)
        return _response.data

    async def get_session(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Session:
        """
        Get a session.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Session
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.get_session(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_session(id, request_options=request_options)
        return _response.data

    async def cancel_session(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Cancel the session.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.cancel_session(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_session(id, request_options=request_options)
        return _response.data

    async def get_session_status(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SessionStatus:
        """
        Get a session's live status.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SessionStatus
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.get_session_status(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_session_status(id, request_options=request_options)
        return _response.data

    async def send_session_messages(
        self,
        id: str,
        *,
        request: SendSessionMessagesRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Send a user message (single or batch).

        Parameters
        ----------
        id : str

        request : SendSessionMessagesRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient
        from hai_agents.sessions import SendSessionMessagesRequestBody_UserMessage

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.send_session_messages(
                id="id",
                request=SendSessionMessagesRequestBody_UserMessage(
                    message="message",
                    type="user_message",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send_session_messages(id, request=request, request_options=request_options)
        return _response.data

    async def send_session_tool_results(
        self,
        id: str,
        *,
        request: SendSessionToolResultsRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Send results for custom tool calls (single or batch).

        Parameters
        ----------
        id : str

        request : SendSessionToolResultsRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient, ToolRequest, ToolResultEvent

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.send_session_tool_results(
                id="id",
                request=ToolResultEvent(
                    tool_req=ToolRequest(
                        tool_name="tool_name",
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send_session_tool_results(
            id, request=request, request_options=request_options
        )
        return _response.data

    async def pause_session(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Pause the session.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.pause_session(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.pause_session(id, request_options=request_options)
        return _response.data

    async def resume_session(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Resume the session.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.resume_session(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resume_session(id, request_options=request_options)
        return _response.data

    async def force_session_answer(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Ask the agent to emit a final answer on its next step.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.force_session_answer(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.force_session_answer(id, request_options=request_options)
        return _response.data

    async def get_session_changes(
        self,
        id: str,
        *,
        from_index: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        include_events: typing.Optional[bool] = None,
        wait_for_seconds: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[SessionChanges]:
        """
        Long-poll for new events since ``from_index``; 204 if none arrive within ``wait_for_seconds``.

        Parameters
        ----------
        id : str

        from_index : typing.Optional[int]

        limit : typing.Optional[int]

        include_events : typing.Optional[bool]

        wait_for_seconds : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[SessionChanges]
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.get_session_changes(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_session_changes(
            id,
            from_index=from_index,
            limit=limit,
            include_events=include_events,
            wait_for_seconds=wait_for_seconds,
            request_options=request_options,
        )
        return _response.data

    async def list_session_events(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        sort: typing.Optional[typing.Sequence[ListSessionEventsRequestSortItem]] = None,
        type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PageSessionEvent:
        """
        Paginated event history. Use ``/changes`` for live tailing.

        Parameters
        ----------
        id : str

        page : typing.Optional[int]

        size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[ListSessionEventsRequestSortItem]]

        type : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageSessionEvent
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.list_session_events(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_session_events(
            id, page=page, size=size, sort=sort, type=type, request_options=request_options
        )
        return _response.data

    async def submit_session_feedback(
        self,
        id: str,
        *,
        success: bool,
        message: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Record semantic-success feedback on the whole session.

        Parameters
        ----------
        id : str

        success : bool

        message : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.submit_session_feedback(
                id="id",
                success=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.submit_session_feedback(
            id, success=success, message=message, request_options=request_options
        )
        return _response.data

    async def submit_event_feedback(
        self,
        id: str,
        event_index: int,
        *,
        success: bool,
        message: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Record feedback on a single event in the session's history.

        Parameters
        ----------
        id : str

        event_index : int

        success : bool

        message : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.submit_event_feedback(
                id="id",
                event_index=1,
                success=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.submit_event_feedback(
            id, event_index, success=success, message=message, request_options=request_options
        )
        return _response.data

    async def share_session(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ShareLink:
        """
        Make the session publicly readable; returns the share URL path.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ShareLink
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.share_session(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.share_session(id, request_options=request_options)
        return _response.data

    async def unshare_session(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Revoke public access to the session.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.unshare_session(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.unshare_session(id, request_options=request_options)
        return _response.data

    async def get_session_resource(
        self, id: str, bucket: str, key: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Redirect to a presigned S3 URL for a session-owned resource.

        Parameters
        ----------
        id : str

        bucket : str

        key : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            Resource bytes. The API redirects to a presigned S3 URL; SDK clients follow the redirect and receive the raw object (e.g. screenshot image bytes).

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            async for _chunk in client.sessions.get_session_resource(
                id="id",
                bucket="bucket",
                key="key",
            ):
                pass


        asyncio.run(main())
        """
        async with self._raw_client.get_session_resource(id, bucket, key, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk
