# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.one_password_config import OnePasswordConfig
from ..types.vault_config_list import VaultConfigList
from ..types.vault_config_read import VaultConfigRead
from ..types.vault_health import VaultHealth
from .raw_client import AsyncRawVaultsClient, RawVaultsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class VaultsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawVaultsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawVaultsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawVaultsClient
        """
        return self._raw_client

    def list_vaults(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VaultConfigList:
        """
        List the caller's org vault configs.

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VaultConfigList
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.vaults.list_vaults()
        """
        _response = self._raw_client.list_vaults(limit=limit, offset=offset, request_options=request_options)
        return _response.data

    def create_vault(
        self,
        *,
        name: str,
        provider_config: OnePasswordConfig,
        token: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VaultConfigRead:
        """
        Create a vault config. The provider token is validated by env-manager before storage.

        Parameters
        ----------
        name : str

        provider_config : OnePasswordConfig

        token : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VaultConfigRead
            Successful Response

        Examples
        --------
        from hai_agents import Client, OnePasswordConfig

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.vaults.create_vault(
            name="name",
            provider_config=OnePasswordConfig(
                op_vault_id="op_vault_id",
            ),
            token="token",
        )
        """
        _response = self._raw_client.create_vault(
            name=name, provider_config=provider_config, token=token, request_options=request_options
        )
        return _response.data

    def get_vault(self, vault_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> VaultConfigRead:
        """
        Fetch a vault config by id.

        Parameters
        ----------
        vault_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VaultConfigRead
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.vaults.get_vault(
            vault_id="vault_id",
        )
        """
        _response = self._raw_client.get_vault(vault_id, request_options=request_options)
        return _response.data

    def delete_vault(self, vault_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a vault config.

        Parameters
        ----------
        vault_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.vaults.delete_vault(
            vault_id="vault_id",
        )
        """
        _response = self._raw_client.delete_vault(vault_id, request_options=request_options)
        return _response.data

    def update_vault(
        self,
        vault_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        provider_config: typing.Optional[OnePasswordConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VaultConfigRead:
        """
        Partial update of a vault config (name and/or provider_config).

        Parameters
        ----------
        vault_id : str

        name : typing.Optional[str]

        provider_config : typing.Optional[OnePasswordConfig]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VaultConfigRead
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.vaults.update_vault(
            vault_id="vault_id",
        )
        """
        _response = self._raw_client.update_vault(
            vault_id, name=name, provider_config=provider_config, request_options=request_options
        )
        return _response.data

    def rotate_vault_token(
        self, vault_id: str, *, token: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Rotate the stored provider token. env-manager health-checks it before writing.

        Parameters
        ----------
        vault_id : str

        token : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.vaults.rotate_vault_token(
            vault_id="vault_id",
            token="token",
        )
        """
        _response = self._raw_client.rotate_vault_token(vault_id, token=token, request_options=request_options)
        return _response.data

    def vault_health(self, vault_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> VaultHealth:
        """
        Probe the vault's provider. Always 200 when reachable; branch on ``ok``.

        Parameters
        ----------
        vault_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VaultHealth
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.vaults.vault_health(
            vault_id="vault_id",
        )
        """
        _response = self._raw_client.vault_health(vault_id, request_options=request_options)
        return _response.data


class AsyncVaultsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawVaultsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawVaultsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawVaultsClient
        """
        return self._raw_client

    async def list_vaults(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VaultConfigList:
        """
        List the caller's org vault configs.

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VaultConfigList
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.vaults.list_vaults()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_vaults(limit=limit, offset=offset, request_options=request_options)
        return _response.data

    async def create_vault(
        self,
        *,
        name: str,
        provider_config: OnePasswordConfig,
        token: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VaultConfigRead:
        """
        Create a vault config. The provider token is validated by env-manager before storage.

        Parameters
        ----------
        name : str

        provider_config : OnePasswordConfig

        token : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VaultConfigRead
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient, OnePasswordConfig

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.vaults.create_vault(
                name="name",
                provider_config=OnePasswordConfig(
                    op_vault_id="op_vault_id",
                ),
                token="token",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_vault(
            name=name, provider_config=provider_config, token=token, request_options=request_options
        )
        return _response.data

    async def get_vault(
        self, vault_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> VaultConfigRead:
        """
        Fetch a vault config by id.

        Parameters
        ----------
        vault_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VaultConfigRead
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.vaults.get_vault(
                vault_id="vault_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_vault(vault_id, request_options=request_options)
        return _response.data

    async def delete_vault(self, vault_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a vault config.

        Parameters
        ----------
        vault_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.vaults.delete_vault(
                vault_id="vault_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_vault(vault_id, request_options=request_options)
        return _response.data

    async def update_vault(
        self,
        vault_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        provider_config: typing.Optional[OnePasswordConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VaultConfigRead:
        """
        Partial update of a vault config (name and/or provider_config).

        Parameters
        ----------
        vault_id : str

        name : typing.Optional[str]

        provider_config : typing.Optional[OnePasswordConfig]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VaultConfigRead
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.vaults.update_vault(
                vault_id="vault_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_vault(
            vault_id, name=name, provider_config=provider_config, request_options=request_options
        )
        return _response.data

    async def rotate_vault_token(
        self, vault_id: str, *, token: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Rotate the stored provider token. env-manager health-checks it before writing.

        Parameters
        ----------
        vault_id : str

        token : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.vaults.rotate_vault_token(
                vault_id="vault_id",
                token="token",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.rotate_vault_token(vault_id, token=token, request_options=request_options)
        return _response.data

    async def vault_health(
        self, vault_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> VaultHealth:
        """
        Probe the vault's provider. Always 200 when reachable; branch on ``ok``.

        Parameters
        ----------
        vault_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VaultHealth
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.vaults.vault_health(
                vault_id="vault_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.vault_health(vault_id, request_options=request_options)
        return _response.data
