# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.token_quota_status import TokenQuotaStatus
from .raw_client import AsyncRawQuotaClient, RawQuotaClient


class QuotaClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawQuotaClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawQuotaClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawQuotaClient
        """
        return self._raw_client

    def get_token_quota(self, *, request_options: typing.Optional[RequestOptions] = None) -> TokenQuotaStatus:
        """
        Return the current org's token-quota snapshot for the FE meter.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TokenQuotaStatus
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.quota.get_token_quota()
        """
        _response = self._raw_client.get_token_quota(request_options=request_options)
        return _response.data


class AsyncQuotaClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawQuotaClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawQuotaClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawQuotaClient
        """
        return self._raw_client

    async def get_token_quota(self, *, request_options: typing.Optional[RequestOptions] = None) -> TokenQuotaStatus:
        """
        Return the current org's token-quota snapshot for the FE meter.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TokenQuotaStatus
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.quota.get_token_quota()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_token_quota(request_options=request_options)
        return _response.data
