# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.page_skill import PageSkill
from ..types.skill import Skill
from .raw_client import AsyncRawSkillsClient, RawSkillsClient
from .types.list_skills_request_sort_item import ListSkillsRequestSortItem

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SkillsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSkillsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSkillsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSkillsClient
        """
        return self._raw_client

    def list_skills(
        self,
        *,
        name: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        sort: typing.Optional[typing.Sequence[ListSkillsRequestSortItem]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PageSkill:
        """
        List reserved + caller's org skills, optionally filtered by name or text search.

        Parameters
        ----------
        name : typing.Optional[str]
            Case-insensitive substring match on skill name.

        search : typing.Optional[str]
            Case-insensitive match on skill name or description.

        page : typing.Optional[int]
            Page number (1-based)

        size : typing.Optional[int]
            Number of items per page

        sort : typing.Optional[typing.Sequence[ListSkillsRequestSortItem]]
            Sort by field

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageSkill
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            token="YOUR_TOKEN",
        )
        client.skills.list_skills()
        """
        _response = self._raw_client.list_skills(
            name=name, search=search, page=page, size=size, sort=sort, request_options=request_options
        )
        return _response.data

    def create_skill(
        self,
        *,
        name: str,
        description: str,
        body: str,
        source: typing.Optional[str] = OMIT,
        url_pattern: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Skill:
        """
        Create a skill. The ``h/`` namespace is reserved for built-in skills.

        Parameters
        ----------
        name : str
            Unique name for this skill in your catalog. Format: lowercase ASCII letters, digits and hyphens; must start and end with alphanumeric; max 63 chars per segment; optional single 'org/' namespace prefix (e.g. 'h/web-environment').

        description : str
            When to use this skill. The agent reads this to decide whether to load it.

        body : str
            Markdown instructions the agent loads when it uses the skill.

        source : typing.Optional[str]
            Optional URL the content was sourced from.

        url_pattern : typing.Optional[str]
            Optional regex hinting at URLs where this skill applies.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Skill
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            token="YOUR_TOKEN",
        )
        client.skills.create_skill(
            name="name",
            description="description",
            body="body",
        )
        """
        _response = self._raw_client.create_skill(
            name=name,
            description=description,
            body=body,
            source=source,
            url_pattern=url_pattern,
            request_options=request_options,
        )
        return _response.data

    def get_skill(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> Skill:
        """
        Fetch by name; 404 if not visible. ``:path`` so slash-containing names round-trip.

        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Skill
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            token="YOUR_TOKEN",
        )
        client.skills.get_skill(
            name="name",
        )
        """
        _response = self._raw_client.get_skill(name, request_options=request_options)
        return _response.data

    def update_skill(
        self,
        name_: str,
        *,
        name: str,
        description: str,
        body: str,
        source: typing.Optional[str] = OMIT,
        url_pattern: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Skill:
        """
        Replace a skill's content. ``name`` must match the URL identifier; renames are not supported.

        Parameters
        ----------
        name_ : str

        name : str
            Unique name for this skill in your catalog. Format: lowercase ASCII letters, digits and hyphens; must start and end with alphanumeric; max 63 chars per segment; optional single 'org/' namespace prefix (e.g. 'h/web-environment').

        description : str
            When to use this skill. The agent reads this to decide whether to load it.

        body : str
            Markdown instructions the agent loads when it uses the skill.

        source : typing.Optional[str]
            Optional URL the content was sourced from.

        url_pattern : typing.Optional[str]
            Optional regex hinting at URLs where this skill applies.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Skill
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            token="YOUR_TOKEN",
        )
        client.skills.update_skill(
            name_="name",
            name="name",
            description="description",
            body="body",
        )
        """
        _response = self._raw_client.update_skill(
            name_,
            name=name,
            description=description,
            body=body,
            source=source,
            url_pattern=url_pattern,
            request_options=request_options,
        )
        return _response.data

    def delete_skill(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete by name. Reserved rows: H employee only.

        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from hai_agents import Client

        client = Client(
            token="YOUR_TOKEN",
        )
        client.skills.delete_skill(
            name="name",
        )
        """
        _response = self._raw_client.delete_skill(name, request_options=request_options)
        return _response.data


class AsyncSkillsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSkillsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSkillsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSkillsClient
        """
        return self._raw_client

    async def list_skills(
        self,
        *,
        name: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        sort: typing.Optional[typing.Sequence[ListSkillsRequestSortItem]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PageSkill:
        """
        List reserved + caller's org skills, optionally filtered by name or text search.

        Parameters
        ----------
        name : typing.Optional[str]
            Case-insensitive substring match on skill name.

        search : typing.Optional[str]
            Case-insensitive match on skill name or description.

        page : typing.Optional[int]
            Page number (1-based)

        size : typing.Optional[int]
            Number of items per page

        sort : typing.Optional[typing.Sequence[ListSkillsRequestSortItem]]
            Sort by field

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PageSkill
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.skills.list_skills()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_skills(
            name=name, search=search, page=page, size=size, sort=sort, request_options=request_options
        )
        return _response.data

    async def create_skill(
        self,
        *,
        name: str,
        description: str,
        body: str,
        source: typing.Optional[str] = OMIT,
        url_pattern: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Skill:
        """
        Create a skill. The ``h/`` namespace is reserved for built-in skills.

        Parameters
        ----------
        name : str
            Unique name for this skill in your catalog. Format: lowercase ASCII letters, digits and hyphens; must start and end with alphanumeric; max 63 chars per segment; optional single 'org/' namespace prefix (e.g. 'h/web-environment').

        description : str
            When to use this skill. The agent reads this to decide whether to load it.

        body : str
            Markdown instructions the agent loads when it uses the skill.

        source : typing.Optional[str]
            Optional URL the content was sourced from.

        url_pattern : typing.Optional[str]
            Optional regex hinting at URLs where this skill applies.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Skill
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.skills.create_skill(
                name="name",
                description="description",
                body="body",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_skill(
            name=name,
            description=description,
            body=body,
            source=source,
            url_pattern=url_pattern,
            request_options=request_options,
        )
        return _response.data

    async def get_skill(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> Skill:
        """
        Fetch by name; 404 if not visible. ``:path`` so slash-containing names round-trip.

        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Skill
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.skills.get_skill(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_skill(name, request_options=request_options)
        return _response.data

    async def update_skill(
        self,
        name_: str,
        *,
        name: str,
        description: str,
        body: str,
        source: typing.Optional[str] = OMIT,
        url_pattern: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Skill:
        """
        Replace a skill's content. ``name`` must match the URL identifier; renames are not supported.

        Parameters
        ----------
        name_ : str

        name : str
            Unique name for this skill in your catalog. Format: lowercase ASCII letters, digits and hyphens; must start and end with alphanumeric; max 63 chars per segment; optional single 'org/' namespace prefix (e.g. 'h/web-environment').

        description : str
            When to use this skill. The agent reads this to decide whether to load it.

        body : str
            Markdown instructions the agent loads when it uses the skill.

        source : typing.Optional[str]
            Optional URL the content was sourced from.

        url_pattern : typing.Optional[str]
            Optional regex hinting at URLs where this skill applies.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Skill
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.skills.update_skill(
                name_="name",
                name="name",
                description="description",
                body="body",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_skill(
            name_,
            name=name,
            description=description,
            body=body,
            source=source,
            url_pattern=url_pattern,
            request_options=request_options,
        )
        return _response.data

    async def delete_skill(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete by name. Reserved rows: H employee only.

        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.skills.delete_skill(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_skill(name, request_options=request_options)
        return _response.data
