# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .active_state_change_data_state import ActiveStateChangeDataState
from .tool_request import ToolRequest


class ActiveStateChangeData(UniversalBaseModel):
    state: ActiveStateChangeDataState
    pending_tool_calls: typing.Optional[typing.List[ToolRequest]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
