# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .active_state_change_data import ActiveStateChangeData


class ActiveStateChangeEvent(UniversalBaseModel):
    """
    The agent switched between running, idle and awaiting custom tool results.
    """

    timestamp: dt.datetime
    data: ActiveStateChangeData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
