# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .answer_event_answer import AnswerEventAnswer
from .image_content import ImageContent
from .json_value import JsonValue
from .message_event_content_item import MessageEventContentItem
from .tool_request import ToolRequest


class AgentEventData_AnswerEvent(UniversalBaseModel):
    kind: typing.Literal["answer_event"] = "answer_event"
    answer: AnswerEventAnswer

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEventData_ErrorEvent(UniversalBaseModel):
    kind: typing.Literal["error_event"] = "error_event"
    error: str
    origin: str
    tool_req: typing.Optional[ToolRequest] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEventData_FlowEvent(UniversalBaseModel):
    kind: typing.Literal["flow_event"] = "flow_event"
    flow: str
    origin: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEventData_MessageEvent(UniversalBaseModel):
    kind: typing.Literal["message_event"] = "message_event"
    caller_id: str
    content: typing.Optional[typing.List[MessageEventContentItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEventData_ObservationEvent(UniversalBaseModel):
    kind: typing.Literal["observation_event"] = "observation_event"
    type: typing.Optional[str] = None
    text: typing.Optional[str] = None
    image: typing.Optional[ImageContent] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEventData_PolicyEvent(UniversalBaseModel):
    kind: typing.Literal["policy_event"] = "policy_event"
    reasoning_content: typing.Optional[str] = None
    content: typing.Optional[str] = None
    tool_reqs: typing.Optional[typing.List[ToolRequest]] = None
    validation_errors: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentEventData_ToolResult(UniversalBaseModel):
    kind: typing.Literal["tool_result"] = "tool_result"
    tool_req: ToolRequest
    result: typing.Optional[JsonValue] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


AgentEventData = typing_extensions.Annotated[
    typing.Union[
        AgentEventData_AnswerEvent,
        AgentEventData_ErrorEvent,
        AgentEventData_FlowEvent,
        AgentEventData_MessageEvent,
        AgentEventData_ObservationEvent,
        AgentEventData_PolicyEvent,
        AgentEventData_ToolResult,
    ],
    pydantic.Field(discriminator="kind"),
]
