# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Android(UniversalBaseModel):
    """
    An Android device the agent controls via touch, keyboard, and screenshots.
    """

    id: str = pydantic.Field()
    """
    Catalog identifier for this environment.
    """

    session_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Connect to an existing Android session by id instead of starting a new one.
    """

    image: typing.Optional[str] = pydantic.Field(default=None)
    """
    Emulator image to boot instead of the default one, e.g. an image with an app preinstalled. Ignored when session_id attaches to an existing session.
    """

    lazy: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Provision on the agent's first use instead of at startup. Skips the initial observation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
