# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BrowserVisualMode(UniversalBaseModel):
    """
    Act on screenshots by viewport coordinates.
    """

    width: typing.Optional[int] = pydantic.Field(default=None)
    """
    Viewport width in pixels.
    """

    height: typing.Optional[int] = pydantic.Field(default=None)
    """
    Viewport height in pixels.
    """

    markdown: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Also include the viewport's text as markdown alongside each screenshot.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
