# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .browser_host import BrowserHost
from .browser_mode import BrowserMode
from .browser_network import BrowserNetwork


class Browser(UniversalBaseModel):
    """
    A web browser the agent navigates and acts on.
    """

    id: str = pydantic.Field()
    """
    Catalog identifier for this environment.
    """

    host: typing.Optional[BrowserHost] = pydantic.Field(default=None)
    """
    Where the browser runs: 'cloud' on H Company infrastructure, or 'user_device' on your own machine.
    """

    start_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Initial URL to open.
    """

    headless: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Run the browser without a visible window.
    """

    session_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Connect to an existing browser session by id instead of starting a new one.
    """

    mode: typing.Optional[BrowserMode] = pydantic.Field(default=None)
    """
    How the agent perceives and drives the browser.
    """

    vault_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Id of a vault config to bind to this browser, letting the agent sign in to sites with secrets resolved from the vault. The vault must belong to the caller's organization. Only supported on cloud-hosted browsers. Omit to run without secret access.
    """

    browser_profile_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Id of a browser profile to load into this browser, restoring saved cookies and storage state from a prior session. The profile must belong to the caller's organization. Only supported on cloud-hosted browsers. Omit to run with a fresh profile.
    """

    use_default_browser_profile: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, load the caller's default browser profile for this browser flavor (marked via the browser-profiles API) instead of naming one explicitly. Mutually exclusive with browser_profile_id. When no default exists, an empty profile is auto-created and marked default; default-profile sessions save their final state back on stop when no other session is already persisting the profile. Only supported on cloud-hosted browsers.
    """

    persist_browser_profile: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When true, the browser profile is updated with this session's final browser state (cookies, storage) when the session ends. Requires browser_profile_id or use_default_browser_profile. Only one active session at a time may persist a given profile; concurrent read-only use is always allowed.
    """

    network: typing.Optional[BrowserNetwork] = pydantic.Field(default=None)
    """
    Optional network configuration for the remote browser session. Applied only when a new runner session is provisioned (not when session_id is set).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
