# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .cron_timing_type import CronTimingType


class CronTiming(UniversalBaseModel):
    """
    Cron cadence evaluated in an IANA timezone.
    """

    type: typing.Optional[CronTimingType] = "cron"
    expression: str = pydantic.Field()
    """
    Five-field cron expression, e.g. '0 9 * * 1-5'.
    """

    timezone: str = pydantic.Field()
    """
    IANA timezone the expression is evaluated in, e.g. 'Europe/Paris'.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
