# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .browser_host import BrowserHost
from .browser_mode import BrowserMode
from .browser_network import BrowserNetwork
from .desktop_host import DesktopHost


class Environment_Desktop(UniversalBaseModel):
    kind: typing.Literal["desktop"] = "desktop"
    id: str
    host: DesktopHost
    session_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Environment_Web(UniversalBaseModel):
    kind: typing.Literal["web"] = "web"
    id: str
    host: typing.Optional[BrowserHost] = None
    start_url: typing.Optional[str] = None
    headless: typing.Optional[bool] = None
    session_id: typing.Optional[str] = None
    mode: typing.Optional[BrowserMode] = None
    vault_id: typing.Optional[str] = None
    browser_profile_id: typing.Optional[str] = None
    use_default_browser_profile: typing.Optional[bool] = None
    persist_browser_profile: typing.Optional[bool] = None
    network: typing.Optional[BrowserNetwork] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


Environment = typing_extensions.Annotated[
    typing.Union[Environment_Desktop, Environment_Web], pydantic.Field(discriminator="kind")
]
