# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FlowEvent(UniversalBaseModel):
    """
    Run-loop control transition (pause, resume, stop, ...).
    """

    flow: str = pydantic.Field()
    """
    Control signal, e.g. "pause", "resume", "force_answer".
    """

    origin: str = pydantic.Field()
    """
    Who triggered the transition.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
