# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .image_content_type import ImageContentType


class ImageContent(UniversalBaseModel):
    """
    Image payload: ``url`` for platform-served screenshots, ``base64`` for inline images.
    """

    source: str = pydantic.Field()
    """
    Image location: a fetchable URL or a base64 payload, per ``type``.
    """

    type: ImageContentType
    media_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    MIME type, e.g. "image/png".
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
