# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .proxy_pool import ProxyPool


class ManagedProxySelection(UniversalBaseModel):
    """
    Request for an H-managed proxy, provisioned per session.

    Describes intent only — pool, country, stickiness — never credentials; H resolves
    and injects those when provisioning the session, including which provider backs
    the requested pool.
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    Two-letter ISO 3166-1 country to source IPs from (e.g. 'US'). Validated server-side.
    """

    sticky: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Keep the same IP across the session where the pool allows it.
    """

    pool: typing.Optional[ProxyPool] = pydantic.Field(default=None)
    """
    Which upstream IP pool to draw from.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
