# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .model_cost import ModelCost


class Metrics(UniversalBaseModel):
    """
    Rolled-up usage and cost for a session.
    """

    steps: typing.Optional[int] = pydantic.Field(default=None)
    """
    Steps taken so far.
    """

    cost_per_model: typing.Optional[typing.List[ModelCost]] = pydantic.Field(default=None)
    """
    Per-model token usage and cost.
    """

    input_cost: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total input cost in USD; null if any model is unpriced.
    """

    output_cost: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total output cost in USD; null if any model is unpriced.
    """

    reasoning_cost: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total reasoning cost in USD; null if any model is unpriced.
    """

    total_cost: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total cost in USD; null if any model is unpriced.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
