# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ModelUsage(UniversalBaseModel):
    """
    Per-model token usage.
    """

    name: str = pydantic.Field()
    """
    Model id.
    """

    input_tokens: int = pydantic.Field()
    """
    Input tokens consumed.
    """

    output_tokens: int = pydantic.Field()
    """
    Output tokens produced.
    """

    reasoning_tokens: int = pydantic.Field()
    """
    Reasoning tokens produced.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
