# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .one_password_config_provider import OnePasswordConfigProvider


class OnePasswordConfig(UniversalBaseModel):
    """
    1Password vault provider config.
    """

    provider: typing.Optional[OnePasswordConfigProvider] = None
    op_vault_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
