# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tool_request import ToolRequest


class PolicyEvent(UniversalBaseModel):
    """
    One policy (LLM) step: the model output plus the tool requests extracted from it.
    """

    reasoning_content: typing.Optional[str] = None
    content: typing.Optional[str] = None
    tool_reqs: typing.Optional[typing.List[ToolRequest]] = None
    validation_errors: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Validation errors raised while parsing the model output.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
