# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .model_usage import ModelUsage
from .trajectory_status import TrajectoryStatus


class SessionStatus(UniversalBaseModel):
    """
    ``GET /api/v2/sessions/{id}/status`` response.
    """

    status: TrajectoryStatus = pydantic.Field()
    """
    Current lifecycle state of the session.
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error message if the session failed; null otherwise.
    """

    steps: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of steps the agent has taken.
    """

    usage_per_model: typing.Optional[typing.List[ModelUsage]] = pydantic.Field(default=None)
    """
    Per-model token usage. Empty until the agent calls a model.
    """

    subagent_session_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Session ids of any subagents this session spawned.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
