# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .active_state_change_data import ActiveStateChangeData
from .agent_completion_data import AgentCompletionData
from .agent_error_data import AgentErrorData
from .agent_event_data import AgentEventData
from .agent_run_status_change_data import AgentRunStatusChangeData
from .agent_started_data import AgentStartedData
from .live_view_url_data import LiveViewUrlData
from .metrics_update_data import MetricsUpdateData
from .request_start_data import RequestStartData
from .request_start_dispatched_data import RequestStartDispatchedData


class SessionEventZero_ActiveStateChangeEvent(UniversalBaseModel):
    type: typing.Literal["ActiveStateChangeEvent"] = "ActiveStateChangeEvent"
    timestamp: dt.datetime
    data: ActiveStateChangeData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SessionEventZero_AgentCompletionEvent(UniversalBaseModel):
    type: typing.Literal["AgentCompletionEvent"] = "AgentCompletionEvent"
    timestamp: dt.datetime
    data: AgentCompletionData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SessionEventZero_AgentErrorEvent(UniversalBaseModel):
    type: typing.Literal["AgentErrorEvent"] = "AgentErrorEvent"
    timestamp: dt.datetime
    data: AgentErrorData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SessionEventZero_AgentEvent(UniversalBaseModel):
    type: typing.Literal["AgentEvent"] = "AgentEvent"
    timestamp: dt.datetime
    data: AgentEventData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SessionEventZero_AgentRunStatusChangeEvent(UniversalBaseModel):
    type: typing.Literal["AgentRunStatusChangeEvent"] = "AgentRunStatusChangeEvent"
    timestamp: dt.datetime
    data: AgentRunStatusChangeData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SessionEventZero_AgentStartedEvent(UniversalBaseModel):
    type: typing.Literal["AgentStartedEvent"] = "AgentStartedEvent"
    timestamp: dt.datetime
    data: AgentStartedData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SessionEventZero_LiveViewUrlEvent(UniversalBaseModel):
    type: typing.Literal["LiveViewUrlEvent"] = "LiveViewUrlEvent"
    timestamp: dt.datetime
    data: LiveViewUrlData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SessionEventZero_MetricsUpdateEvent(UniversalBaseModel):
    type: typing.Literal["MetricsUpdateEvent"] = "MetricsUpdateEvent"
    timestamp: dt.datetime
    data: MetricsUpdateData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SessionEventZero_RequestStartDispatchedEvent(UniversalBaseModel):
    type: typing.Literal["RequestStartDispatchedEvent"] = "RequestStartDispatchedEvent"
    timestamp: dt.datetime
    data: RequestStartDispatchedData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SessionEventZero_RequestStartEvent(UniversalBaseModel):
    type: typing.Literal["RequestStartEvent"] = "RequestStartEvent"
    timestamp: dt.datetime
    data: RequestStartData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


SessionEventZero = typing_extensions.Annotated[
    typing.Union[
        SessionEventZero_ActiveStateChangeEvent,
        SessionEventZero_AgentCompletionEvent,
        SessionEventZero_AgentErrorEvent,
        SessionEventZero_AgentEvent,
        SessionEventZero_AgentRunStatusChangeEvent,
        SessionEventZero_AgentStartedEvent,
        SessionEventZero_LiveViewUrlEvent,
        SessionEventZero_MetricsUpdateEvent,
        SessionEventZero_RequestStartDispatchedEvent,
        SessionEventZero_RequestStartEvent,
    ],
    pydantic.Field(discriminator="type"),
]
