# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .session_request_agent import SessionRequestAgent
from .session_request_messages import SessionRequestMessages


class SessionRequest(UniversalBaseModel):
    """
    ``POST /api/v2/sessions`` body.
    """

    agent: SessionRequestAgent = pydantic.Field()
    """
    Agent to run: a registered agent's name, or an inline Agent definition.
    """

    messages: typing.Optional[SessionRequestMessages] = pydantic.Field(default=None)
    """
    Initial task for the agent. A plain string, a single message, or a list of messages.
    """

    max_steps: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum reasoning steps the agent may take. Unbounded if null.
    """

    max_time_s: typing.Optional[float] = pydantic.Field(default=None)
    """
    Maximum wall-clock seconds the agent may run. Unbounded if null.
    """

    idle_timeout_s: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seconds to keep the session open for follow-up messages after each answer. Null ends the session as soon as the agent answers.
    """

    delete_after_min: typing.Optional[int] = pydantic.Field(default=None)
    """
    Minutes after the session finishes before it is automatically deleted. Defaults to 30 days. Null keeps the session forever.
    """

    delete_screenshot_after_min: typing.Optional[int] = pydantic.Field(default=None)
    """
    Minutes after the session finishes before its screenshots are deleted. Defaults to 30 days. Null keeps screenshots for the session's lifetime.
    """

    queue: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When the organization is at its concurrent-session limit, accept this session into a queue (status 'queued') instead of rejecting it with 429. Queued sessions start automatically, oldest first, as running sessions finish. Set to false to get an immediate 429 when no slot is available.
    """

    group_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional id to group and list related sessions together.
    """

    parent_session_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Id of the parent session, when this is a child run.
    """

    overrides: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Per-run overrides applied to the resolved request, keyed by a dotted path. List members are selected with an explicit [field=value] clause, e.g. {"agent.environments[kind=web].start_url": "https://bing.com"}. Each value must match the type of the field its path targets.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


update_forward_refs(SessionRequest)
