# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Skill(UniversalBaseModel):
    """
    A named, reusable instruction an agent can draw on during a session.
    """

    name: str = pydantic.Field()
    """
    Unique name for this skill in your catalog. Format: lowercase ASCII letters, digits and hyphens; must start and end with alphanumeric; max 63 chars per segment; optional single 'org/' namespace prefix (e.g. 'h/web-environment').
    """

    description: str = pydantic.Field()
    """
    When to use this skill. The agent reads this to decide whether to load it.
    """

    body: str = pydantic.Field()
    """
    Markdown instructions the agent loads when it uses the skill.
    """

    source: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional URL the content was sourced from.
    """

    url_pattern: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional regex hinting at URLs where this skill applies.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
