# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .workstation_host import WorkstationHost


class Workstation(UniversalBaseModel):
    """
    A desktop computer with a browser, office apps and a shell, which the agent drives from that shell.
    """

    id: str = pydantic.Field()
    """
    Catalog identifier for this environment.
    """

    host: typing.Optional[WorkstationHost] = pydantic.Field(default=None)
    """
    Where the workstation runs: 'cloud' on H Company infrastructure, or 'user_device' on your own machine.
    """

    session_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Connect to an existing workstation session by id instead of starting a new one.
    """

    lazy: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Provision on the agent's first use instead of at startup. Cloud workstations only.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
