# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_environment_request import (
        CreateEnvironmentRequest,
        CreateEnvironmentRequest_Desktop,
        CreateEnvironmentRequest_Web,
    )
    from .list_environments_request_sort_item import ListEnvironmentsRequestSortItem
    from .patch_environment_host import PatchEnvironmentHost
    from .patch_environment_mode import PatchEnvironmentMode, PatchEnvironmentMode_Text, PatchEnvironmentMode_Visual
    from .update_environment_request_body import (
        UpdateEnvironmentRequestBody,
        UpdateEnvironmentRequestBody_Desktop,
        UpdateEnvironmentRequestBody_Web,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "CreateEnvironmentRequest": ".create_environment_request",
    "CreateEnvironmentRequest_Desktop": ".create_environment_request",
    "CreateEnvironmentRequest_Web": ".create_environment_request",
    "ListEnvironmentsRequestSortItem": ".list_environments_request_sort_item",
    "PatchEnvironmentHost": ".patch_environment_host",
    "PatchEnvironmentMode": ".patch_environment_mode",
    "PatchEnvironmentMode_Text": ".patch_environment_mode",
    "PatchEnvironmentMode_Visual": ".patch_environment_mode",
    "UpdateEnvironmentRequestBody": ".update_environment_request_body",
    "UpdateEnvironmentRequestBody_Desktop": ".update_environment_request_body",
    "UpdateEnvironmentRequestBody_Web": ".update_environment_request_body",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateEnvironmentRequest",
    "CreateEnvironmentRequest_Desktop",
    "CreateEnvironmentRequest_Web",
    "ListEnvironmentsRequestSortItem",
    "PatchEnvironmentHost",
    "PatchEnvironmentMode",
    "PatchEnvironmentMode_Text",
    "PatchEnvironmentMode_Visual",
    "UpdateEnvironmentRequestBody",
    "UpdateEnvironmentRequestBody_Desktop",
    "UpdateEnvironmentRequestBody_Web",
]
