# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.browser_text_mode import BrowserTextMode
from ...types.browser_visual_mode import BrowserVisualMode

PatchEnvironmentMode = typing.Union[BrowserVisualMode, BrowserTextMode]
