# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PatchEnvironmentMode_Text(UniversalBaseModel):
    type: typing.Literal["text"] = "text"
    chunk_size: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PatchEnvironmentMode_Visual(UniversalBaseModel):
    type: typing.Literal["visual"] = "visual"
    width: typing.Optional[int] = None
    height: typing.Optional[int] = None
    markdown: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


PatchEnvironmentMode = typing_extensions.Annotated[
    typing.Union[PatchEnvironmentMode_Text, PatchEnvironmentMode_Visual], pydantic.Field(discriminator="type")
]
