# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.browser_kind import BrowserKind
from ..types.browser_mode import BrowserMode
from ..types.environment import Environment
from ..types.environment_kind import EnvironmentKind
from ..types.environment_page import EnvironmentPage
from .raw_client import AsyncRawEnvironmentsClient, RawEnvironmentsClient
from .types.list_environments_request_sort_item import ListEnvironmentsRequestSortItem

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EnvironmentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEnvironmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEnvironmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEnvironmentsClient
        """
        return self._raw_client

    def list_environments(
        self,
        *,
        id: typing.Optional[str] = None,
        kind: typing.Optional[EnvironmentKind] = None,
        search: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        sort: typing.Optional[typing.Sequence[ListEnvironmentsRequestSortItem]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EnvironmentPage:
        """
        List reserved + caller's org environments.

        Parameters
        ----------
        id : typing.Optional[str]
            Case-insensitive substring match on environment id.

        kind : typing.Optional[EnvironmentKind]
            Filter by environment kind.

        search : typing.Optional[str]
            Case-insensitive match on environment id or description.

        page : typing.Optional[int]
            Page number (1-based)

        size : typing.Optional[int]
            Number of items per page

        sort : typing.Optional[typing.Sequence[ListEnvironmentsRequestSortItem]]
            Sort by field

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnvironmentPage
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.environments.list_environments()
        """
        _response = self._raw_client.list_environments(
            id=id, kind=kind, search=search, page=page, size=size, sort=sort, request_options=request_options
        )
        return _response.data

    def create_environment(
        self,
        *,
        id: str,
        headless: bool,
        width: int,
        height: int,
        kind: typing.Optional[BrowserKind] = OMIT,
        start_url: typing.Optional[str] = OMIT,
        mode: typing.Optional[BrowserMode] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Environment:
        """
        Create an environment.

        Parameters
        ----------
        id : str
            Catalog identifier for this environment.

        headless : bool
            Run without a visible window.

        width : int
            Viewport width in pixels.

        height : int
            Viewport height in pixels.

        kind : typing.Optional[BrowserKind]

        start_url : typing.Optional[str]
            Initial URL to open. Null starts on a blank page.

        mode : typing.Optional[BrowserMode]
            How the agent perceives and drives the browser. 'visual': act on screenshots by viewport coordinates. 'multimodal': the same, with the page also included as markdown text alongside each screenshot. 'text': read-only markdown with URL navigation, no screenshots.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Environment
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.environments.create_environment(
            id="id",
            headless=True,
            width=1,
            height=1,
        )
        """
        _response = self._raw_client.create_environment(
            id=id,
            headless=headless,
            width=width,
            height=height,
            kind=kind,
            start_url=start_url,
            mode=mode,
            request_options=request_options,
        )
        return _response.data

    def get_environment(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Environment:
        """
        Fetch by identifier; 404 if not visible. ``:path`` so slash-containing ids round-trip.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Environment
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.environments.get_environment(
            id="id",
        )
        """
        _response = self._raw_client.get_environment(id, request_options=request_options)
        return _response.data

    def update_environment(
        self,
        id_: str,
        *,
        id: str,
        headless: bool,
        width: int,
        height: int,
        kind: typing.Optional[BrowserKind] = OMIT,
        start_url: typing.Optional[str] = OMIT,
        mode: typing.Optional[BrowserMode] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Environment:
        """
        Replace the environment spec.

        Parameters
        ----------
        id_ : str

        id : str
            Catalog identifier for this environment.

        headless : bool
            Run without a visible window.

        width : int
            Viewport width in pixels.

        height : int
            Viewport height in pixels.

        kind : typing.Optional[BrowserKind]

        start_url : typing.Optional[str]
            Initial URL to open. Null starts on a blank page.

        mode : typing.Optional[BrowserMode]
            How the agent perceives and drives the browser. 'visual': act on screenshots by viewport coordinates. 'multimodal': the same, with the page also included as markdown text alongside each screenshot. 'text': read-only markdown with URL navigation, no screenshots.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Environment
            Successful Response

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.environments.update_environment(
            id_="id",
            id="id",
            headless=True,
            width=1,
            height=1,
        )
        """
        _response = self._raw_client.update_environment(
            id_,
            id=id,
            headless=headless,
            width=width,
            height=height,
            kind=kind,
            start_url=start_url,
            mode=mode,
            request_options=request_options,
        )
        return _response.data

    def delete_environment(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete by identifier. Reserved rows: H employee only.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from hai_agents import Client

        client = Client(
            api_key="YOUR_API_KEY",
        )
        client.environments.delete_environment(
            id="id",
        )
        """
        _response = self._raw_client.delete_environment(id, request_options=request_options)
        return _response.data


class AsyncEnvironmentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEnvironmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEnvironmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEnvironmentsClient
        """
        return self._raw_client

    async def list_environments(
        self,
        *,
        id: typing.Optional[str] = None,
        kind: typing.Optional[EnvironmentKind] = None,
        search: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        sort: typing.Optional[typing.Sequence[ListEnvironmentsRequestSortItem]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EnvironmentPage:
        """
        List reserved + caller's org environments.

        Parameters
        ----------
        id : typing.Optional[str]
            Case-insensitive substring match on environment id.

        kind : typing.Optional[EnvironmentKind]
            Filter by environment kind.

        search : typing.Optional[str]
            Case-insensitive match on environment id or description.

        page : typing.Optional[int]
            Page number (1-based)

        size : typing.Optional[int]
            Number of items per page

        sort : typing.Optional[typing.Sequence[ListEnvironmentsRequestSortItem]]
            Sort by field

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnvironmentPage
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.environments.list_environments()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_environments(
            id=id, kind=kind, search=search, page=page, size=size, sort=sort, request_options=request_options
        )
        return _response.data

    async def create_environment(
        self,
        *,
        id: str,
        headless: bool,
        width: int,
        height: int,
        kind: typing.Optional[BrowserKind] = OMIT,
        start_url: typing.Optional[str] = OMIT,
        mode: typing.Optional[BrowserMode] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Environment:
        """
        Create an environment.

        Parameters
        ----------
        id : str
            Catalog identifier for this environment.

        headless : bool
            Run without a visible window.

        width : int
            Viewport width in pixels.

        height : int
            Viewport height in pixels.

        kind : typing.Optional[BrowserKind]

        start_url : typing.Optional[str]
            Initial URL to open. Null starts on a blank page.

        mode : typing.Optional[BrowserMode]
            How the agent perceives and drives the browser. 'visual': act on screenshots by viewport coordinates. 'multimodal': the same, with the page also included as markdown text alongside each screenshot. 'text': read-only markdown with URL navigation, no screenshots.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Environment
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.environments.create_environment(
                id="id",
                headless=True,
                width=1,
                height=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_environment(
            id=id,
            headless=headless,
            width=width,
            height=height,
            kind=kind,
            start_url=start_url,
            mode=mode,
            request_options=request_options,
        )
        return _response.data

    async def get_environment(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Environment:
        """
        Fetch by identifier; 404 if not visible. ``:path`` so slash-containing ids round-trip.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Environment
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.environments.get_environment(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_environment(id, request_options=request_options)
        return _response.data

    async def update_environment(
        self,
        id_: str,
        *,
        id: str,
        headless: bool,
        width: int,
        height: int,
        kind: typing.Optional[BrowserKind] = OMIT,
        start_url: typing.Optional[str] = OMIT,
        mode: typing.Optional[BrowserMode] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Environment:
        """
        Replace the environment spec.

        Parameters
        ----------
        id_ : str

        id : str
            Catalog identifier for this environment.

        headless : bool
            Run without a visible window.

        width : int
            Viewport width in pixels.

        height : int
            Viewport height in pixels.

        kind : typing.Optional[BrowserKind]

        start_url : typing.Optional[str]
            Initial URL to open. Null starts on a blank page.

        mode : typing.Optional[BrowserMode]
            How the agent perceives and drives the browser. 'visual': act on screenshots by viewport coordinates. 'multimodal': the same, with the page also included as markdown text alongside each screenshot. 'text': read-only markdown with URL navigation, no screenshots.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Environment
            Successful Response

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.environments.update_environment(
                id_="id",
                id="id",
                headless=True,
                width=1,
                height=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_environment(
            id_,
            id=id,
            headless=headless,
            width=width,
            height=height,
            kind=kind,
            start_url=start_url,
            mode=mode,
            request_options=request_options,
        )
        return _response.data

    async def delete_environment(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete by identifier. Reserved rows: H employee only.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from hai_agents import AsyncClient

        client = AsyncClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.environments.delete_environment(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_environment(id, request_options=request_options)
        return _response.data
