# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.browser_mode import BrowserMode


class UpdateEnvironmentResponse_Web(UniversalBaseModel):
    kind: typing.Literal["web"] = "web"
    id: str
    headless: bool
    width: int
    height: int
    start_url: typing.Optional[str] = None
    mode: typing.Optional[BrowserMode] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


UpdateEnvironmentResponse = UpdateEnvironmentResponse_Web
