# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .agent import Agent
    from .agent_environments_item import AgentEnvironmentsItem
    from .agent_environments_item_one import AgentEnvironmentsItemOne, AgentEnvironmentsItemOne_Web
    from .agent_skills_item import AgentSkillsItem
    from .agent_subagents_item import AgentSubagentsItem
    from .browser import Browser
    from .browser_mode import BrowserMode
    from .environment_kind import EnvironmentKind
    from .environment_page import EnvironmentPage
    from .environment_page_items_item import EnvironmentPageItemsItem, EnvironmentPageItemsItem_Web
    from .feedback import Feedback
    from .http_validation_error import HttpValidationError
    from .metrics import Metrics
    from .model_cost import ModelCost
    from .model_usage import ModelUsage
    from .page_agent import PageAgent
    from .page_session_summary import PageSessionSummary
    from .page_skill import PageSkill
    from .page_trajectory_event import PageTrajectoryEvent
    from .quota_status import QuotaStatus
    from .quota_status_scope import QuotaStatusScope
    from .session import Session
    from .session_request import SessionRequest
    from .session_request_agent import SessionRequestAgent
    from .session_request_messages import SessionRequestMessages
    from .session_status import SessionStatus
    from .session_summary import SessionSummary
    from .share_link import ShareLink
    from .skill import Skill
    from .trajectory_changes import TrajectoryChanges
    from .trajectory_changes_answer import TrajectoryChangesAnswer
    from .trajectory_event import TrajectoryEvent
    from .trajectory_status import TrajectoryStatus
    from .user_message_batch import UserMessageBatch
    from .user_message_event import UserMessageEvent
    from .user_message_event_type import UserMessageEventType
    from .validation_error import ValidationError
    from .validation_error_loc_item import ValidationErrorLocItem
_dynamic_imports: typing.Dict[str, str] = {
    "Agent": ".agent",
    "AgentEnvironmentsItem": ".agent_environments_item",
    "AgentEnvironmentsItemOne": ".agent_environments_item_one",
    "AgentEnvironmentsItemOne_Web": ".agent_environments_item_one",
    "AgentSkillsItem": ".agent_skills_item",
    "AgentSubagentsItem": ".agent_subagents_item",
    "Browser": ".browser",
    "BrowserMode": ".browser_mode",
    "EnvironmentKind": ".environment_kind",
    "EnvironmentPage": ".environment_page",
    "EnvironmentPageItemsItem": ".environment_page_items_item",
    "EnvironmentPageItemsItem_Web": ".environment_page_items_item",
    "Feedback": ".feedback",
    "HttpValidationError": ".http_validation_error",
    "Metrics": ".metrics",
    "ModelCost": ".model_cost",
    "ModelUsage": ".model_usage",
    "PageAgent": ".page_agent",
    "PageSessionSummary": ".page_session_summary",
    "PageSkill": ".page_skill",
    "PageTrajectoryEvent": ".page_trajectory_event",
    "QuotaStatus": ".quota_status",
    "QuotaStatusScope": ".quota_status_scope",
    "Session": ".session",
    "SessionRequest": ".session_request",
    "SessionRequestAgent": ".session_request_agent",
    "SessionRequestMessages": ".session_request_messages",
    "SessionStatus": ".session_status",
    "SessionSummary": ".session_summary",
    "ShareLink": ".share_link",
    "Skill": ".skill",
    "TrajectoryChanges": ".trajectory_changes",
    "TrajectoryChangesAnswer": ".trajectory_changes_answer",
    "TrajectoryEvent": ".trajectory_event",
    "TrajectoryStatus": ".trajectory_status",
    "UserMessageBatch": ".user_message_batch",
    "UserMessageEvent": ".user_message_event",
    "UserMessageEventType": ".user_message_event_type",
    "ValidationError": ".validation_error",
    "ValidationErrorLocItem": ".validation_error_loc_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Agent",
    "AgentEnvironmentsItem",
    "AgentEnvironmentsItemOne",
    "AgentEnvironmentsItemOne_Web",
    "AgentSkillsItem",
    "AgentSubagentsItem",
    "Browser",
    "BrowserMode",
    "EnvironmentKind",
    "EnvironmentPage",
    "EnvironmentPageItemsItem",
    "EnvironmentPageItemsItem_Web",
    "Feedback",
    "HttpValidationError",
    "Metrics",
    "ModelCost",
    "ModelUsage",
    "PageAgent",
    "PageSessionSummary",
    "PageSkill",
    "PageTrajectoryEvent",
    "QuotaStatus",
    "QuotaStatusScope",
    "Session",
    "SessionRequest",
    "SessionRequestAgent",
    "SessionRequestMessages",
    "SessionStatus",
    "SessionSummary",
    "ShareLink",
    "Skill",
    "TrajectoryChanges",
    "TrajectoryChangesAnswer",
    "TrajectoryEvent",
    "TrajectoryStatus",
    "UserMessageBatch",
    "UserMessageEvent",
    "UserMessageEventType",
    "ValidationError",
    "ValidationErrorLocItem",
]
