# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_environments_item_one import AgentEnvironmentsItemOne

AgentEnvironmentsItem = typing.Union[str, AgentEnvironmentsItemOne]
