# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs
from .agent_environments_item import AgentEnvironmentsItem
from .agent_skills_item import AgentSkillsItem


class Agent(UniversalBaseModel):
    """
    Declarative agent definition.
    """

    name: str = pydantic.Field()
    """
    Unique name for this agent in your catalog. Format: lowercase ASCII letters, digits and hyphens; must start and end with alphanumeric; max 63 chars per segment; optional single 'org/' namespace prefix (e.g. 'h/web-environment').
    """

    description: str = pydantic.Field()
    """
    What the agent does. Parent agents read this to decide when to delegate to it.
    """

    environments: typing.List[AgentEnvironmentsItem] = pydantic.Field()
    """
    Environments the agent runs in. Each entry is a registered environment's id or an inline definition. At most one per kind. Required unless the agent delegates to subagents (a pure orchestrator owns none).
    """

    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    Model that serves the agent. Defaults to the platform model if omitted.
    """

    instructions: typing.Optional[str] = pydantic.Field(default=None)
    """
    Instructions appended to the agent's system prompt to steer behavior.
    """

    subagents: typing.Optional[typing.List["AgentSubagentsItem"]] = pydantic.Field(default=None)
    """
    Agents this one can delegate to. Each entry is a registered agent's name or an inline definition.
    """

    skills: typing.Optional[typing.List[AgentSkillsItem]] = pydantic.Field(default=None)
    """
    Skills the agent can draw on. Each entry is a registered skill's name or an inline definition.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .agent_subagents_item import AgentSubagentsItem  # noqa: E402, I001

update_forward_refs(Agent, AgentSubagentsItem=AgentSubagentsItem)
