# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .browser_mode import BrowserMode


class Browser(UniversalBaseModel):
    """
    A web browser the agent navigates and acts on.
    """

    id: str = pydantic.Field()
    """
    Catalog identifier for this environment.
    """

    headless: bool = pydantic.Field()
    """
    Run without a visible window.
    """

    width: int = pydantic.Field()
    """
    Viewport width in pixels.
    """

    height: int = pydantic.Field()
    """
    Viewport height in pixels.
    """

    start_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Initial URL to open. Null starts on a blank page.
    """

    mode: typing.Optional[BrowserMode] = pydantic.Field(default=None)
    """
    How the agent perceives and drives the browser. 'visual': act on screenshots by viewport coordinates. 'multimodal': the same, with the page also included as markdown text alongside each screenshot. 'text': read-only markdown with URL navigation, no screenshots.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
