# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ModelCost(UniversalBaseModel):
    """
    Token usage and cost for a single model.
    """

    name: str = pydantic.Field()
    """
    Model id.
    """

    input_tokens: int = pydantic.Field()
    """
    Input tokens consumed.
    """

    output_tokens: int = pydantic.Field()
    """
    Output tokens produced.
    """

    reasoning_tokens: int = pydantic.Field()
    """
    Reasoning tokens produced.
    """

    input_cost: typing.Optional[float] = pydantic.Field(default=None)
    """
    Input cost in USD; null if the model is unpriced.
    """

    output_cost: typing.Optional[float] = pydantic.Field(default=None)
    """
    Output cost in USD; null if the model is unpriced.
    """

    reasoning_cost: typing.Optional[float] = pydantic.Field(default=None)
    """
    Reasoning cost in USD; null if the model is unpriced.
    """

    total_cost: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total cost in USD; null if the model is unpriced.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
