# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        Agent,
        AgentEnvironmentsItem,
        AgentSkillsItem,
        AgentSubagentsItem,
        Browser,
        BrowserMode,
        Environment,
        EnvironmentKind,
        EnvironmentPage,
        Environment_Web,
        Feedback,
        HttpValidationError,
        Metrics,
        ModelCost,
        ModelUsage,
        PageAgent,
        PageSessionSummary,
        PageSkill,
        PageTrajectoryEvent,
        QuotaStatus,
        QuotaStatusScope,
        Session,
        SessionRequest,
        SessionRequestAgent,
        SessionRequestMessages,
        SessionStatus,
        SessionSummary,
        ShareLink,
        Skill,
        TrajectoryChanges,
        TrajectoryChangesAnswer,
        TrajectoryEvent,
        TrajectoryStatus,
        UserMessageBatch,
        UserMessageEvent,
        UserMessageEventType,
        ValidationError,
        ValidationErrorLocItem,
    )
    from .errors import UnprocessableEntityError
    from . import agents, environments, sessions, skills
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .agents import ListAgentsRequestSortItem
    from .client import AsyncClient, Client
    from .environment import HaiAgentsEnvironment
    from .environments import (
        CreateEnvironmentRequest,
        CreateEnvironmentRequest_Web,
        ListEnvironmentsRequestSortItem,
        UpdateEnvironmentRequestBody,
        UpdateEnvironmentRequestBody_Web,
    )
    from .polling import (
        MAX_REQUEST_BYTES,
        SessionRunResult,
        TERMINAL_SESSION_STATUSES,
        assert_request_under_limit,
        async_run_session_until_done,
        async_wait_for_session,
        is_terminal_session_status,
        run_session_until_done,
        wait_for_session,
    )
    from .sessions import (
        ListSessionEventsRequestSortItem,
        ListSessionsRequestOwner,
        ListSessionsRequestSortItem,
        SendSessionMessagesRequestBody,
        SendSessionMessagesRequestBody_Batch,
        SendSessionMessagesRequestBody_UserMessage,
    )
    from .skills import ListSkillsRequestSortItem
_dynamic_imports: typing.Dict[str, str] = {
    "Agent": ".types",
    "AgentEnvironmentsItem": ".types",
    "AgentSkillsItem": ".types",
    "AgentSubagentsItem": ".types",
    "AsyncClient": ".client",
    "Browser": ".types",
    "BrowserMode": ".types",
    "Client": ".client",
    "CreateEnvironmentRequest": ".environments",
    "CreateEnvironmentRequest_Web": ".environments",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "Environment": ".types",
    "EnvironmentKind": ".types",
    "EnvironmentPage": ".types",
    "Environment_Web": ".types",
    "Feedback": ".types",
    "HaiAgentsEnvironment": ".environment",
    "HttpValidationError": ".types",
    "ListAgentsRequestSortItem": ".agents",
    "ListEnvironmentsRequestSortItem": ".environments",
    "ListSessionEventsRequestSortItem": ".sessions",
    "ListSessionsRequestOwner": ".sessions",
    "ListSessionsRequestSortItem": ".sessions",
    "ListSkillsRequestSortItem": ".skills",
    "MAX_REQUEST_BYTES": ".polling",
    "Metrics": ".types",
    "ModelCost": ".types",
    "ModelUsage": ".types",
    "PageAgent": ".types",
    "PageSessionSummary": ".types",
    "PageSkill": ".types",
    "PageTrajectoryEvent": ".types",
    "QuotaStatus": ".types",
    "QuotaStatusScope": ".types",
    "SendSessionMessagesRequestBody": ".sessions",
    "SendSessionMessagesRequestBody_Batch": ".sessions",
    "SendSessionMessagesRequestBody_UserMessage": ".sessions",
    "Session": ".types",
    "SessionRequest": ".types",
    "SessionRequestAgent": ".types",
    "SessionRequestMessages": ".types",
    "SessionRunResult": ".polling",
    "SessionStatus": ".types",
    "SessionSummary": ".types",
    "ShareLink": ".types",
    "Skill": ".types",
    "TERMINAL_SESSION_STATUSES": ".polling",
    "TrajectoryChanges": ".types",
    "TrajectoryChangesAnswer": ".types",
    "TrajectoryEvent": ".types",
    "TrajectoryStatus": ".types",
    "UnprocessableEntityError": ".errors",
    "UpdateEnvironmentRequestBody": ".environments",
    "UpdateEnvironmentRequestBody_Web": ".environments",
    "UserMessageBatch": ".types",
    "UserMessageEvent": ".types",
    "UserMessageEventType": ".types",
    "ValidationError": ".types",
    "ValidationErrorLocItem": ".types",
    "agents": ".agents",
    "assert_request_under_limit": ".polling",
    "async_run_session_until_done": ".polling",
    "async_wait_for_session": ".polling",
    "environments": ".environments",
    "is_terminal_session_status": ".polling",
    "run_session_until_done": ".polling",
    "sessions": ".sessions",
    "skills": ".skills",
    "wait_for_session": ".polling",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Agent",
    "AgentEnvironmentsItem",
    "AgentSkillsItem",
    "AgentSubagentsItem",
    "AsyncClient",
    "Browser",
    "BrowserMode",
    "Client",
    "CreateEnvironmentRequest",
    "CreateEnvironmentRequest_Web",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "Environment",
    "EnvironmentKind",
    "EnvironmentPage",
    "Environment_Web",
    "Feedback",
    "HaiAgentsEnvironment",
    "HttpValidationError",
    "ListAgentsRequestSortItem",
    "ListEnvironmentsRequestSortItem",
    "ListSessionEventsRequestSortItem",
    "ListSessionsRequestOwner",
    "ListSessionsRequestSortItem",
    "ListSkillsRequestSortItem",
    "MAX_REQUEST_BYTES",
    "Metrics",
    "ModelCost",
    "ModelUsage",
    "PageAgent",
    "PageSessionSummary",
    "PageSkill",
    "PageTrajectoryEvent",
    "QuotaStatus",
    "QuotaStatusScope",
    "SendSessionMessagesRequestBody",
    "SendSessionMessagesRequestBody_Batch",
    "SendSessionMessagesRequestBody_UserMessage",
    "Session",
    "SessionRequest",
    "SessionRequestAgent",
    "SessionRequestMessages",
    "SessionRunResult",
    "SessionStatus",
    "SessionSummary",
    "ShareLink",
    "Skill",
    "TERMINAL_SESSION_STATUSES",
    "TrajectoryChanges",
    "TrajectoryChangesAnswer",
    "TrajectoryEvent",
    "TrajectoryStatus",
    "UnprocessableEntityError",
    "UpdateEnvironmentRequestBody",
    "UpdateEnvironmentRequestBody_Web",
    "UserMessageBatch",
    "UserMessageEvent",
    "UserMessageEventType",
    "ValidationError",
    "ValidationErrorLocItem",
    "agents",
    "assert_request_under_limit",
    "async_run_session_until_done",
    "async_wait_for_session",
    "environments",
    "is_terminal_session_status",
    "run_session_until_done",
    "sessions",
    "skills",
    "wait_for_session",
]
