# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import os
import typing

import httpx
from .core.api_error import ApiError
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import HaiAgentsEnvironment

if typing.TYPE_CHECKING:
    from .agents.client import AgentsClient, AsyncAgentsClient
    from .browser_profiles.client import AsyncBrowserProfilesClient, BrowserProfilesClient
    from .environments.client import AsyncEnvironmentsClient, EnvironmentsClient
    from .quota.client import AsyncQuotaClient, QuotaClient
    from .sessions.client import AsyncSessionsClient, SessionsClient
    from .skills.client import AsyncSkillsClient, SkillsClient
    from .vaults.client import AsyncVaultsClient, VaultsClient
    from .webhooks.client import AsyncWebhooksClient, WebhooksClient


class BaseClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : HaiAgentsEnvironment
        The environment to use for requests from the client. from .environment import HaiAgentsEnvironment



        Defaults to HaiAgentsEnvironment.EU



    api_key : typing.Optional[typing.Union[str, typing.Callable[[], str]]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from hai_agents import Client

    client = Client(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: HaiAgentsEnvironment = HaiAgentsEnvironment.EU,
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = None,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        if api_key is None:
            api_key = os.getenv("HAI_API_KEY")
        if api_key is None:
            raise ApiError(body="The client must be instantiated be either passing in api_key or setting HAI_API_KEY")
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            logging=logging,
        )
        self._sessions: typing.Optional[SessionsClient] = None
        self._skills: typing.Optional[SkillsClient] = None
        self._environments: typing.Optional[EnvironmentsClient] = None
        self._agents: typing.Optional[AgentsClient] = None
        self._webhooks: typing.Optional[WebhooksClient] = None
        self._browser_profiles: typing.Optional[BrowserProfilesClient] = None
        self._vaults: typing.Optional[VaultsClient] = None
        self._quota: typing.Optional[QuotaClient] = None

    @property
    def sessions(self):
        if self._sessions is None:
            from .sessions.client import SessionsClient  # noqa: E402

            self._sessions = SessionsClient(client_wrapper=self._client_wrapper)
        return self._sessions

    @property
    def skills(self):
        if self._skills is None:
            from .skills.client import SkillsClient  # noqa: E402

            self._skills = SkillsClient(client_wrapper=self._client_wrapper)
        return self._skills

    @property
    def environments(self):
        if self._environments is None:
            from .environments.client import EnvironmentsClient  # noqa: E402

            self._environments = EnvironmentsClient(client_wrapper=self._client_wrapper)
        return self._environments

    @property
    def agents(self):
        if self._agents is None:
            from .agents.client import AgentsClient  # noqa: E402

            self._agents = AgentsClient(client_wrapper=self._client_wrapper)
        return self._agents

    @property
    def webhooks(self):
        if self._webhooks is None:
            from .webhooks.client import WebhooksClient  # noqa: E402

            self._webhooks = WebhooksClient(client_wrapper=self._client_wrapper)
        return self._webhooks

    @property
    def browser_profiles(self):
        if self._browser_profiles is None:
            from .browser_profiles.client import BrowserProfilesClient  # noqa: E402

            self._browser_profiles = BrowserProfilesClient(client_wrapper=self._client_wrapper)
        return self._browser_profiles

    @property
    def vaults(self):
        if self._vaults is None:
            from .vaults.client import VaultsClient  # noqa: E402

            self._vaults = VaultsClient(client_wrapper=self._client_wrapper)
        return self._vaults

    @property
    def quota(self):
        if self._quota is None:
            from .quota.client import QuotaClient  # noqa: E402

            self._quota = QuotaClient(client_wrapper=self._client_wrapper)
        return self._quota


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncBaseClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : HaiAgentsEnvironment
        The environment to use for requests from the client. from .environment import HaiAgentsEnvironment



        Defaults to HaiAgentsEnvironment.EU



    api_key : typing.Optional[typing.Union[str, typing.Callable[[], str]]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    async_token : typing.Optional[typing.Callable[[], typing.Awaitable[str]]]
        An async callable that returns a bearer token. Use this when token acquisition involves async I/O (e.g., refreshing tokens via an async HTTP client). When provided, this is used instead of the synchronous token for async requests.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from hai_agents import AsyncClient

    client = AsyncClient(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: HaiAgentsEnvironment = HaiAgentsEnvironment.EU,
        api_key: typing.Optional[typing.Union[str, typing.Callable[[], str]]] = None,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        async_token: typing.Optional[typing.Callable[[], typing.Awaitable[str]]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        if api_key is None:
            api_key = os.getenv("HAI_API_KEY")
        if api_key is None:
            raise ApiError(body="The client must be instantiated be either passing in api_key or setting HAI_API_KEY")
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            async_token=async_token,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            logging=logging,
        )
        self._sessions: typing.Optional[AsyncSessionsClient] = None
        self._skills: typing.Optional[AsyncSkillsClient] = None
        self._environments: typing.Optional[AsyncEnvironmentsClient] = None
        self._agents: typing.Optional[AsyncAgentsClient] = None
        self._webhooks: typing.Optional[AsyncWebhooksClient] = None
        self._browser_profiles: typing.Optional[AsyncBrowserProfilesClient] = None
        self._vaults: typing.Optional[AsyncVaultsClient] = None
        self._quota: typing.Optional[AsyncQuotaClient] = None

    @property
    def sessions(self):
        if self._sessions is None:
            from .sessions.client import AsyncSessionsClient  # noqa: E402

            self._sessions = AsyncSessionsClient(client_wrapper=self._client_wrapper)
        return self._sessions

    @property
    def skills(self):
        if self._skills is None:
            from .skills.client import AsyncSkillsClient  # noqa: E402

            self._skills = AsyncSkillsClient(client_wrapper=self._client_wrapper)
        return self._skills

    @property
    def environments(self):
        if self._environments is None:
            from .environments.client import AsyncEnvironmentsClient  # noqa: E402

            self._environments = AsyncEnvironmentsClient(client_wrapper=self._client_wrapper)
        return self._environments

    @property
    def agents(self):
        if self._agents is None:
            from .agents.client import AsyncAgentsClient  # noqa: E402

            self._agents = AsyncAgentsClient(client_wrapper=self._client_wrapper)
        return self._agents

    @property
    def webhooks(self):
        if self._webhooks is None:
            from .webhooks.client import AsyncWebhooksClient  # noqa: E402

            self._webhooks = AsyncWebhooksClient(client_wrapper=self._client_wrapper)
        return self._webhooks

    @property
    def browser_profiles(self):
        if self._browser_profiles is None:
            from .browser_profiles.client import AsyncBrowserProfilesClient  # noqa: E402

            self._browser_profiles = AsyncBrowserProfilesClient(client_wrapper=self._client_wrapper)
        return self._browser_profiles

    @property
    def vaults(self):
        if self._vaults is None:
            from .vaults.client import AsyncVaultsClient  # noqa: E402

            self._vaults = AsyncVaultsClient(client_wrapper=self._client_wrapper)
        return self._vaults

    @property
    def quota(self):
        if self._quota is None:
            from .quota.client import AsyncQuotaClient  # noqa: E402

            self._quota = AsyncQuotaClient(client_wrapper=self._client_wrapper)
        return self._quota


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: HaiAgentsEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
